# -*- coding: utf-8 -*-
"""getDomains.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1to7IFWTnbLG1IpfOgJ-tWrGM1FD8DatC
"""

#This code gets newly registered domains of that day from whoisds.com and puts it under domains directory with the name domain-names.txt

import zipfile
import pathlib
import requests
from io import BytesIO
from io import StringIO
from datetime import date
from bs4 import BeautifulSoup
import os
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from pyvirtualdisplay import Display
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import codecs
import re
from selenium.webdriver.common.by import By

chrome_options = Options()
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--headless')
chrome_options.add_argument('--disable-dev-shm-usage')

prefs = {"download.default_directory" : "/home/domains/"}
chrome_options.add_experimental_option("prefs",prefs)

d = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=chrome_options)

CURRENT_PATH = pathlib.Path().resolve()
today = date.today().strftime("%Y-%m-%d")
file_path = '/home/domains/'
def ScrapTodaysDomainsFileLink(URL):
    d.get(URL)
    html = d.page_source
    soup = BeautifulSoup(html, features="html.parser")
    domains_table_rows = soup.findAll('tr')

    if domains_table_rows[1].contents[5].text != today:
        raise Exception("No domain file with the current date!")
    if int(domains_table_rows[1].contents[3].text) <= 0:
        raise Exception("0 domains in the file with the current date")

    return domains_table_rows[1].contents[7].a['href']

def DownloadDomainList(link):
    get_zip = requests.get(link)
    zip_file = zipfile.ZipFile(BytesIO(get_zip.content))
    zip_file.extractall(str(file_path))
    

a = ScrapTodaysDomainsFileLink("https://whoisds.com/newly-registered-domains")
DownloadDomainList(a)