# -*- coding: utf-8 -*-
"""Virustotal1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Aew7J-pByzG7DdTYB5Dua3bh8rp74W0f
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/ENS 491 Phishing detection/domains.csv')

df.drop(columns=df.columns[0], axis=1,  inplace=True)

df

n = int(len(df.index)/4 ) + 1

df1 = df.iloc[:n]

pip install virustotal_python

df1

pip install requests

import requests
import time
import json
import pandas
import os

whoisdsVirusTotalDF = pd.DataFrame().assign(URL=df1['domain'])

url_list = whoisdsVirusTotalDF.values.tolist()

cols = ['URL', 'Status','Total Detect','Total Engine']
dat = pd.DataFrame(columns = cols)


API_key = '5fb3d6528a3627ba433571cce649fe727a01d002fc7d18c9c95f728fbb6fbe0d'
url = 'https://www.virustotal.com/vtapi/v2/url/report'


parameters = {'apikey': API_key, 'resource': url_list}

for i in url_list:
  i = i[0]
  parameters = {'apikey': API_key, 'resource': i}

  response= requests.get(url=url, params=parameters)
  if response.status_code == 403:
    print("Error from server: " + str(response.content))
    a = "Not Found"
    b = "-"
    c = "-"
  else:
    json_response= json.loads(response.text)
  
    if json_response['response_code'] <= 0:
      a = "Not Found"
      b = "-"
      c = "-"
    elif json_response['response_code'] >= 1:
      if json_response['positives'] <= 0:
        a = "Clean"
        b = "0"
        c = "90"
      else:
        a = "Malicious"
        b = str(json_response['positives'])
        c = "90"
  dat = dat.append({'URL': i, 'Status':a,'Total Detect':b, 'Total Engine':c,},ignore_index=True)

  time.sleep(15)

dat

dat.to_csv('/content/drive/MyDrive/ENS 491 Phishing detection/virustotal1v3.csv')